#pragma once

#include "../shared/wifi.h"
#include "util.h"

#define WS_SERVER_MAX_CHANNELS 4
#define WS_SERVER_PORT_STR WS_MTS(WS_SERVER_PORT)

#define WS_DMA_RX_BUFFER_SIZE 100
#define WS_DMA_TX_BUFFER_SIZE 1024

#define WS_BACKLOG_SIZE (24 * 60)

#define WS_PINOUT_I2C_SDA_PIN GPIO_PIN_9
#define WS_PINOUT_I2C_SDA_PORT GPIOB
#define WS_PINOUT_I2C_SCL_PIN GPIO_PIN_8
#define WS_PINOUT_I2C_SCL_PORT GPIOB

#define WS_PINOUT_USART1_RX_PIN GPIO_PIN_10
#define WS_PINOUT_USART1_RX_PORT GPIOA
#define WS_PINOUT_USART1_TX_PIN GPIO_PIN_9
#define WS_PINOUT_USART1_TX_PORT GPIOA

#define WS_PINOUT_USART2_RX_PIN GPIO_PIN_3
#define WS_PINOUT_USART2_RX_PORT GPIOA
#define WS_PINOUT_USART2_TX_PIN GPIO_PIN_2
#define WS_PINOUT_USART2_TX_PORT GPIOA

// print esp communication over usb serial (green for tx, red for rx)
#define WS_DBG_PRINT_ESP_OVER_USART2
