#pragma once

#include "wifi.h"

#define WS_PINOUT_I2C_SDA_PIN GPIO_PIN_9
#define WS_PINOUT_I2C_SDA_PORT GPIOB
#define WS_PINOUT_I2C_SCL_PIN GPIO_PIN_8
#define WS_PINOUT_I2C_SCL_PORT GPIOB

#define WS_PINOUT_USART1_RX_PIN GPIO_PIN_10
#define WS_PINOUT_USART1_RX_PORT GPIOA
#define WS_PINOUT_USART1_TX_PIN GPIO_PIN_9
#define WS_PINOUT_USART1_TX_PORT GPIOA

#define WS_PINOUT_USART2_RX_PIN GPIO_PIN_3
#define WS_PINOUT_USART2_RX_PORT GPIOA
#define WS_PINOUT_USART2_TX_PIN GPIO_PIN_2
#define WS_PINOUT_USART2_TX_PORT GPIOA

